### ISSUE TITLE
YNAB API no longer providing dicts?

### ISSUE THREAD

**Issue by luther84** [andreroggeri/ynab-sdk-python#142]
Recently tried out the ynab homeassistant integration via the HACS addon and saw this in the logs

```
some homeassistant stacktrace...
....
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/budgets.py", line 13, in get_budgets
    return BudgetSummaryResponse.from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 102, in from_dict
    data = Data.from_dict(obj.get("data"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 91, in from_dict
    budgets = parsers.from_list(Budget.from_dict, obj.get("budgets"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/utils/parsers.py", line 47, in from_list
    return [f(y) for y in x]
            ^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 72, in from_dict
    currency_format = CurrencyFormat.from_dict(obj.get("currency_format"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 21, in from_dict
    assert isinstance(obj, dict)
           ^^^^^^^^^^^^^^^^^^^^^
```

I checked out the repo for the homeassistant integration and found a handy little script to test the sdk directly (which I also learned was this one)
https://github.com/wxt9861/ynab/blob/master/apitest.py

When I run the following script from a python virtualenv after `pip install ynab-sdk`
```
from ynab_sdk import YNAB

try:
    api_key = "$MY_API_KEY"
    apicheck = YNAB(api_key)
    print(apicheck.budgets.get_budgets())
    data = apicheck.budgets.get_budget("BUDGET_ID")
    print(data.data.budget.id)
except Exception:
    raise
```

I see the following error
```
Traceback (most recent call last):
  File "/home/eman/Projects/ha/ynab_test/api_test", line 6, in <module>
    print(apicheck.budgets.get_budgets())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/budgets.py", line 13, in get_budgets
    return BudgetSummaryResponse.from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 102, in from_dict
    data = Data.from_dict(obj.get("data"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 91, in from_dict
    budgets = parsers.from_list(Budget.from_dict, obj.get("budgets"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/utils/parsers.py", line 47, in from_list
    return [f(y) for y in x]
            ^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 72, in from_dict
    currency_format = CurrencyFormat.from_dict(obj.get("currency_format"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 21, in from_dict
    assert isinstance(obj, dict)
           ^^^^^^^^^^^^^^^^^^^^^
```

Not a python developer so I started pasting things into Claude and it suggested that "Based on the error you're encountering and the content of the budget_summary.py file, it appears that the currency_format field in the API response is not a dictionary as expected."

Claude suggested changes to budget_summary.py such as modifying the **CurrencyFormat.from_dict** method like so
```
@staticmethod
def from_dict(obj: Any) -> "CurrencyFormat":
    if not isinstance(obj, dict):
        # Log a warning or print a message
        print(f"Warning: currency_format is not a dict. Received: {obj}")
        # Return a default CurrencyFormat
        return CurrencyFormat("", "", 0, "", False, "", "", False)
    
    iso_code = parsers.from_str(obj.get("iso_code", ""))
    example_format = parsers.from_str(obj.get("example_format", ""))
    decimal_digits = parsers.from_int(obj.get("decimal_digits", 0))
    decimal_separator = parsers.from_str(obj.get("decimal_separator", ""))
    symbol_first = parsers.from_bool(obj.get("symbol_first", False))
    group_separator = parsers.from_str(obj.get("group_separator", ""))
    currency_symbol = parsers.from_str(obj.get("currency_symbol", ""))
    display_symbol = parsers.from_bool(obj.get("display_symbol", False))
    return CurrencyFormat(
        iso_code,
        example_format,
        decimal_digits,
        decimal_separator,
        symbol_first,
        group_separator,
        currency_symbol,
        display_symbol,
    )
```

Following it's advice I also modified the **Budget.from_dict** and **DateFormat.from_dict** with similar changes. These changes did seem to work. The script now returned some information about my budget but was still returning errors.

```
Traceback (most recent call last):
  File "/home/eman/Projects/ha/ynab_test/api_test", line 7, in <module>
    data = apicheck.budgets.get_budget("BUDGET_ID")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/budgets.py", line 17, in get_budget
    return BudgetDetailResponse.from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_detail.py", line 505, in from_dict
    data = Data.from_dict(obj.get("data"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eman/Projects/ha/ynab_test/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_detail.py", line 492, in from_dict
    assert isinstance(obj, dict)
           ^^^^^^^^^^^^^^^^^^^^^
```

Claude recommends similar changes to the **from_dict** methods in *budget_detail.py* but I gave up at this point and came here to ask if you could update this sdk. I don't know how many of us users there are but I know my wife would really appreciate if I could get his working. Thanks for your time!

**Comment by andreroggeri** [comment]
Hmmm I'm not sure whats going on there.

I ran the following script and it returned the data correctly. According with the API spec, the currency format should be an object ([see here](https://api.ynab.com/v1#/Budgets/getBudgetById))

```py
from ynab_sdk import YNAB

if __name__ == "__main__":
    ynab = YNAB("the API key")

    result = ynab.budgets.get_budgets()
    
    budget_dets = ynab.budgets.get_budget(result.data.budgets[0].id)
    
    print(budget_dets)

    print(result)

```

**Comment by luther84** [comment]
ah #$(*&(

yeah, that script works for me, and to boot, when I look more closely at the other test script I had forgotten to sub out "BUDGET_ID" for my actual budget id. When I do that everything works great. :facepalm: 

I'll note that both scripts produced this as a first line
```
Warning: currency_format is not a dict. Received: None
```

but otherwise both seemed to do the thing, no more error messages. Time to head back to the integration and start troubleshooting there. I'm sorry for generating the issue, thanks for responding and a huge thanks for making it in the first place. I appreciate you!
